"""User-selected US-only scope. Cross-venue mechanisms are not silently transplanted."""
US_ONLY=True
US_BASKETS={'temperature-band-ladder-coherence','multi-outcome-overround-shorting-dutch-book-lay','cross-market-mutually-exclusive-sum-over-one-fade'}
US_CANDIDATES=set('''base-rate-exploitation mean-reversion-on-volatile-markets momentum-trend-following sports-analytics-model kelly-optimal-sizing adverse-selection-adjusted-spread-sizing hidden-markov-regime-detection-for-volatility-switching ensemble-forecast-vs-market-implied-edge brier-score-calibration-harvesting order-flow-imbalance-microstructure-model bayesian-sequential-update-probability-engine gradient-boosted-resolution-classifier particle-filter-nowcasting-for-live-events resolution-correlation-budgeted-sizing volatility-targeted-book-scaling liquidity-adjusted-position-limits scenario-stress-allocation-engine cross-market-net-exposure-netting closing-line-value-harvest weather-adjusted-totals-for-outdoor-games live-in-game-win-probability-divergence rest-travel-and-schedule-fatigue-model playoff-seeding-combinatorial-tree-solver bracket-path-and-group-draw-model ensemble-spread-probability-trading climatology-anchor-for-long-dated-weather weather-event-markets drawdown-circuit-breaker-governor injury-report-wire-race starting-lineup-and-goalie-confirmation-snap series-length-distribution-model'''.split())

def restrict_catalog(rows):
    result=[]
    for r in rows:
        if r['id'] not in US_CANDIDATES|US_BASKETS and r['id'] not in ['shin','benter','fundamental','avellaneda-stoikov']:continue
        row=dict(r,status='US adaptation pending',evaluator=None,note='Research candidate for the US venue. Requires a matching listed US contract and US validation. Previous international results do not establish US profitability.')
        if r['id'] in ['momentum-trend-following','mean-reversion-on-volatile-markets']:row.update(status='US feasibility + forward paper',note='Price-only US approximation with fees, delayed quote screening and separate forward paper. The initial sample lost money; historical depth and independent validation remain missing.')
        if r['id'] in ['weather-event-markets','ensemble-spread-probability-trading']:row.update(status='US CLI forecast component',note='US contract prose, standard-time climate days, CLI parsing and 31/51/40-member forecasts implemented. Separate historical GFS/NAM MOS calibration improved temperature error but lost $10 in the six-date price pilot. Ensemble calibration and executable edge remain unverified.')
        if r['id'] in ['benter','shin']:row.update(status='US historical comparison',note='Separate US weather probability and profit study registered with prior forecast training, August probability fitting and nine September test dates. Benter uses a disclosed regularized adaptation; Shin exchange-ask assumptions remain unverified. Audited Benter scenario: +$17.25 trading, -$47.19 after overhead; historical fills unverified. No forward promotion.')
        if r['id'] in US_BASKETS:row.update(status='US basket historical screen',note='US single-instrument temperature ladder evaluator with exact partition checks, per-leg fees, delayed coherent price checks and partial-fill worst-loss enumeration. Nine-date historical screen found zero qualifying after-cost signals. No CTF, margin credit, verified fills or live profit claim.')
        result.append(row)
    return result
