const {chromium}=require('C:/Users/gamev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=require('path').resolve(__dirname,'../docs/screenshots')+'/';
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});const p=await b.newPage({viewport:{width:1536,height:1024}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8788');await p.getByRole('heading',{name:'Backtest performance'}).waitFor();await p.screenshot({path:out+'polylab-desktop.png'});
await p.getByRole('navigation').getByRole('button',{name:'Strategies',exact:true}).click();await p.getByLabel('Search strategies').fill('Shin');await p.getByRole('button',{name:'Shin Odds Probabilities',exact:true}).click();await p.getByRole('dialog').waitFor();await p.getByRole('button',{name:'Close strategy details'}).click();
await p.getByRole('navigation').getByRole('button',{name:'Papers',exact:true}).click();await p.getByRole('button',{name:'Compare probabilities'}).click();await p.getByText('53.5',{exact:false}).first().waitFor();
await p.getByRole('navigation').getByRole('button',{name:'Agent',exact:true}).click();await p.getByRole('heading',{name:'Does the agent add value?'}).waitFor();await p.screenshot({path:out+'polylab-agent.png'});
await p.getByRole('navigation').getByRole('button',{name:'Weather archive',exact:true}).click();await p.getByRole('button',{name:'Replay',exact:true}).first().click();await p.getByRole('heading',{name:'Order-book replay'}).waitFor();await p.getByLabel('Replay position').fill('10');await p.screenshot({path:out+'polylab-weather.png',fullPage:true});await p.getByRole('button',{name:'Backtest this archive',exact:true}).click();await p.getByRole('alert').waitFor();
await p.getByRole('navigation').getByRole('button',{name:'Backtests',exact:true}).click();await p.getByLabel('Backtest strategy').selectOption('momentum-trend-following');const downloadPromise=p.waitForEvent('download');await p.getByRole('link',{name:'Export CSV'}).click();const dl=await downloadPromise;await dl.saveAs(out+'polylab-ledger.csv');
await p.getByRole('button',{name:'Run backtest',exact:true}).click();await p.getByRole('button',{name:'Run backtest',exact:true}).waitFor({state:'visible'});await p.getByRole('heading',{name:'Trade ledger',exact:true}).waitFor();
await p.setViewportSize({width:390,height:844});await p.getByRole('navigation').getByRole('button',{name:'Overview',exact:true}).click();await p.screenshot({path:out+'polylab-mobile.png',fullPage:true});const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);console.log(JSON.stringify({errors,overflow,title:await p.title(),checks:['search and strategy details','Shin calculator','agent comparison','weather replay slider','trade CSV export','rerun backtest','mobile viewport']}));await b.close()})().catch(e=>{console.error(e);process.exit(1)});

