import React,{useMemo,useState,useEffect} from 'react';
import {Search,ChevronRight,X,ExternalLink} from 'lucide-react';
import {money} from './Chart.jsx';
export default function StrategyTable({catalog,results,compact=false,onSelect,onEvaluate}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('All categories'),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[implemented,setImplemented]=useState(false);
 useEffect(()=>{if(!selected)return;const key=e=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const items=[...document.querySelectorAll('.modal button,.modal a')].filter(x=>!x.disabled);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[selected]);
 const filtered=useMemo(()=>catalog.filter(s=>(category==='All categories'||s.category===category)&&(!implemented||s.status!=='Research specification')&&(s.name+' '+s.description).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(!!results[b.id])-Number(!!results[a.id])||a.name.localeCompare(b.name)),[catalog,search,category,implemented,results]);
 const size=compact?6:15,shown=filtered.slice(page*size,(page+1)*size);
 return <section className="panel library"><div className="section-title"><h2>Strategy library <span className="count">{catalog.length}</span></h2><label className="search"><Search size={16}/><input aria-label="Search strategies" placeholder="Search strategies…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><select aria-label="Strategy category" value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}>{['All categories',...new Set(catalog.map(s=>s.category))].map(c=><option key={c}>{c}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Strategy</th><th>Family</th><th>Implementation</th><th>Realized P&amp;L</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{shown.map(s=><tr key={s.id}><td><button className="row-link" onClick={()=>setSelected(s)}>{s.name}</button></td><td>{s.category}</td><td><span className={'status '+(s.status==='Backtest adapter'?'teal':'muted')}>{s.status==='Backtest adapter'?'●':'○'} {s.status}</span></td><td>{results[s.id]&&s.status==='Backtest adapter'?<span className={results[s.id].realized_pnl<0?'negative':''}>{money(results[s.id].realized_pnl)}<small>{results[s.id].trades} simulated entries</small></span>:'—'}</td><td><button className="icon-button" aria-label={'Details for '+s.name} onClick={()=>setSelected(s)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table>{!shown.length&&<div className="empty">No strategies match these filters.</div>}</div><div className="table-footer"><label><input type="checkbox" checked={implemented} onChange={e=>{setImplemented(e.target.checked);setPage(0)}}/> Show implemented methods</label><span>{filtered.length?`${page*size+1}–${Math.min((page+1)*size,filtered.length)}`:'0'} of {filtered.length}</span><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button disabled={(page+1)*size>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="strategy-title" onClick={e=>e.stopPropagation()}><button className="icon-button close" aria-label="Close strategy details" onClick={()=>setSelected(null)} autoFocus><X/></button><h2 id="strategy-title">{selected.name}</h2><p>{selected.description}</p><p className="notice">{selected.note||selected.status}</p><h3>Required evidence</h3><ul>{selected.requirements?.map((x,i)=><li key={i}>{x}</li>)}</ul><a href={selected.url} target="_blank" rel="noreferrer">Read original method <ExternalLink size={14}/></a>{selected.evaluator==='coherence'&&<button className="primary" onClick={()=>{onEvaluate(selected.id);setSelected(null)}}>Open basket evaluator</button>}{results[selected.id]&&selected.status==='Backtest adapter'&&<button className="primary" onClick={()=>{onSelect(selected.id);setSelected(null)}}>View backtest</button>}</section></div>}</section>
}
