import React,{useEffect,useState} from 'react';
const money=v=>Number(v).toLocaleString('en-US',{style:'currency',currency:'USD'});
export default function USAllocationStudy(){
 const [report,setReport]=useState(null),[slip,setSlip]=useState('0');
 useEffect(()=>{let active=true;fetch('/research/allocation-report.json').then(r=>r.ok?r.json():null).then(r=>{if(active&&r?.audit?.status==='passed')setReport(r)}).catch(()=>{});return()=>{active=false}},[]);
 if(!report)return null;
 const rows=report.results.filter(r=>r.slippage_per_side===slip);
 return <section className="panel detail-panel"><h2>Five-city dollar-profit allocation</h2><p>New York, Chicago, Los Angeles, Miami and San Francisco compete for one $50 account. Every city is evaluated at 02:15 UTC, with a $40 reserve and $5 city cap. The optimizer targets expected dollar profit; the baseline divides the budget equally across eligible cities.</p><p className="notice">Retrospective exploration on already-known September 8–16 outcomes. Prices do not prove historical fills or depth. This is not forward paper profit.</p><label>Slippage per side <select aria-label="Five-city allocation slippage" value={slip} onChange={e=>setSlip(e.target.value)}><option value="0">None added</option><option value=".005">Half a cent</option></select></label><div className="table-scroll"><table><thead><tr><th>Allocation</th><th>Entries / exits</th><th>Profit after trading fees</th><th>Cash</th><th>Open basis</th></tr></thead><tbody>{rows.map(r=><tr key={r.strategy}><td>{r.strategy.replaceAll('_',' ')}</td><td>{r.entries} / {r.exits}</td><td>{money(r.realized_pnl)}</td><td>{money(r.cash)}</td><td>{money(r.open_basis)}</td></tr>)}</tbody></table></div><p>No subscription expense. {report.coverage.filter(c=>c.complete_signal).length} of {report.coverage.length} city-dates had complete price ladders. These accounts are alternatives; their profits cannot be added together.</p><img src="/research/allocation-profit.png" alt="Five-city shared-account backtest profit for expected-dollar and equal-budget allocations under two slippage assumptions" style={{width:'100%',height:'auto'}}/><details><summary>Allocation checks and evidence</summary><p>{report.audit.checks} source, accounting and allocation checks passed. A separate integer solver verifies each optimized selection. Selections use signal-time prices only; later quotes may cancel or reduce entries, without replacements. The probability model is unchanged. Settlement availability remains an historical assumption.</p><a href="/research/allocation-report.json" target="_blank" rel="noreferrer">Open complete backtest report and ledger</a></details></section>
}
