import React,{useEffect,useState} from 'react';
const dollars=value=>Number(value).toLocaleString('en-US',{style:'currency',currency:'USD'});
export default function USBenterStudy(){
 const [report,setReport]=useState(null),[slippage,setSlippage]=useState('0');
 useEffect(()=>{let active=true;fetch('/api/us/benter').then(r=>r.ok?r.json():null).then(r=>{if(active)setReport(r)}).catch(()=>{});return()=>{active=false}},[]);
 if(!report)return null;
 const rows=report.results.filter(r=>r.slippage_per_side===slippage),model=report.combination_model;
 return <section className="panel detail-panel"><h2>US forecast + market test</h2><p>Separate forecast training, probability fitting, and nine September profit-test dates. Benter combines forecast and market probabilities; Shin is an exchange-ask benchmark with unverified bookmaker assumptions.</p><p className="notice">{model?`Combination fitted on ${model.calibration_dates} eligible dates: forecast weight ${model.alpha.toFixed(3)}, market weight ${model.beta.toFixed(3)}.`:`Combination unavailable: ${report.fit_error}. Zero Benter trades here are not a tested return.`} Historical fills and forecast publication timing remain unverified. No strategy is promoted to forward paper trading.</p><label>Slippage per side <select aria-label="US combination slippage" value={slippage} onChange={e=>setSlippage(e.target.value)}><option value="0">None added</option><option value=".005">Half a cent</option></select></label><div className="table-scroll"><table><thead><tr><th>Strategy</th><th>Entries / exits</th><th>Trading P&amp;L</th><th>Open basis</th></tr></thead><tbody>{rows.map(r=><tr key={r.strategy}><td>{r.strategy.replaceAll('_',' ')}{r.strategy==='benter'&&!model?' (unavailable)':''}</td><td>{r.entries} / {r.exits}</td><td>{dollars(r.realized_pnl)}</td><td>{dollars(r.open_basis)}</td></tr>)}</tbody></table></div><details><summary>Archived graph with hypothetical $200/month sensitivity (not a real expense)</summary><a href="/api/us/benter/chart" target="_blank" rel="noreferrer"><img src="/api/us/benter/chart" alt="Registered US forecast and market probability strategy profit comparison; open full-size graph" style={{width:'100%',height:'auto'}}/></a></details><details><summary>Combination study coverage and assumptions</summary><p>{report.coverage.filter(r=>r.role==='calibration').length} registered calibration dates · {report.eligible_calibration_dates} eligible calibration dates · {report.coverage.filter(r=>r.role==='test'&&r.complete_signal).length} test dates with complete signals. The prior losing six-date pilot is excluded.</p><ul>{report.limitations.map(t=><li key={t}>{t}</li>)}</ul></details></section>
}
