import React,{useEffect,useState} from 'react';
const money=v=>Number(v).toLocaleString('en-US',{style:'currency',currency:'USD'});
const cities={KMDW:'Chicago',KLAX:'Los Angeles',KMIA:'Miami',KSFO:'San Francisco'};
export default function USPortfolioStudy(){
 const [report,setReport]=useState(null),[transfer,setTransfer]=useState(null),[slip,setSlip]=useState('0');
 useEffect(()=>{let active=true;Promise.all(['/api/us/portfolio','/api/us/transfer'].map(url=>fetch(url).then(r=>r.ok?r.json():null).catch(()=>null))).then(([a,b])=>{if(active){setReport(a?.results?a:null);setTransfer(b?.results?b:null)}});return()=>{active=false}},[]);
 if(!report)return null;
 const rows=report.results.filter(r=>r.slippage_per_side===slip),cityRows=transfer?.results.filter(r=>r.slippage_per_side===slip)||[];
 return <section className="panel detail-panel"><h2>US shared-capital profit test</h2><p>Four cities compete for one $50 account per strategy, with a $40 cash reserve and $5 entry cap. The New York model weights stay fixed. Market recalibration removes the independent forecast input.</p><p className="notice">Historical price scenarios, with current fees and unverified fills. These cities share the New York test period. Results are audited research comparisons; forward profitability remains unproven.</p><label>Slippage per side <select aria-label="US portfolio slippage" value={slip} onChange={e=>setSlip(e.target.value)}><option value="0">None added</option><option value=".005">Half a cent</option></select></label><div className="table-scroll"><table><thead><tr><th>Strategy</th><th>Entries / exits</th><th>Trading P&amp;L</th><th>Open basis</th></tr></thead><tbody>{rows.map(r=><tr key={r.strategy}><td>{r.strategy.replaceAll('_',' ')}</td><td>{r.entries} / {r.exits}</td><td>{money(r.realized_pnl)}</td><td>{money(r.open_basis)}</td></tr>)}</tbody></table></div><p>No subscription expense is configured; trading fees and selected slippage still count. The chart includes both slippage cases; comparison accounts are alternatives and cannot be added together.</p><img src="/research/portfolio-trading.png" alt="Four-city backtest profit after fees and selected slippage; no subscription expense" style={{width:'100%',height:'auto'}}/><details><summary>Archived graph with hypothetical $200/month sensitivity (not a real expense)</summary><a href="/api/us/portfolio/chart" target="_blank" rel="noreferrer"><img src="/api/us/portfolio/chart" alt="Four-city shared-capital profit curves before and after subscription, with both slippage cases" style={{width:'100%',height:'auto'}}/></a></details><details><summary>Separate city tests and coverage</summary><p>Legacy graph subscription deductions are hypothetical and are excluded from current profit reporting.</p><p>{report.coverage.filter(c=>c.complete_signal).length} of {report.coverage.length} station-dates had complete signals. Below, each city starts its own $50 comparison account. These results do not describe the shared account above.</p><div className="table-scroll"><table><thead><tr><th>City</th><th>Strategy</th><th>Entries / exits</th><th>Trading P&amp;L</th></tr></thead><tbody>{cityRows.map(r=><tr key={r.station+r.strategy}><td>{cities[r.station]||r.station}</td><td>{r.strategy.replaceAll('_',' ')}</td><td>{r.entries} / {r.exits}</td><td>{money(r.realized_pnl)}</td></tr>)}</tbody></table></div><p><a href={'/api/us/transfer/chart?slippage='+encodeURIComponent(slip)} target="_blank" rel="noreferrer">Open city profit graph for selected slippage</a></p><ul>{report.limitations.map(t=><li key={t}>{t}</li>)}</ul></details></section>
}
